version: 2
jobs:
  test:
      docker:
        - image: circleci/python:3.6
      steps:
        - checkout
        - run: pip install --user tox
        - run: python3 -m tox -- -k "not test_examples_experiment" -v 
workflows:
  version: 2
  build:
    jobs:
      - test
