version: 2
jobs:
  test:
      docker:
        - image: circleci/python:3.6
      steps:
        - checkout
        - run: pip install --user tox
        - run: aws configure --region us-east-1
        - run: python3 -m tox -- -m "not end2end"
workflows:
  version: 2
  build:
    jobs:
      - test
