name: examples_tests

on:
  schedule:
    - cron: '0 0 * * *'
 
jobs:
  examples:
    name: Examples tests

    timeout-minutes: 360
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies and run examples tests with tox
      run: |
        python -m pip install --upgrade pip
        pip install tox awscli
        python3 -m awscli configure set region us-east-1
        python3 -m tox -- -v -m "examples"
