name: Run slow tests 

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:    
      - master
 
jobs:
  examples:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r --upgrade requirements.txt
        pip install -r --upgrade tests/requirements.txt
        pip install tox
    - name: Text examples
      run: |
        python3 -m tox -- -v -m "examples"
