name: test_suite

on: [push]

jobs:
  unit:
    name: Unit tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies and run unit tests with tox
      run: |
        python -m pip install --upgrade pip
        pip install tox awscli
        python3 -m awscli configure set region us-east-1
        python3 -m tox -- -v -m "not end2end and not examples"


  end2end:
    name: end2end tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies and run end2end tests with tox
      run: |
        python -m pip install --upgrade pip
        pip install tox awscli
        python3 -m awscli configure set region us-east-1
        python3 -m tox -- -v -m "end2end"
